-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost
-- Üretim Zamanı: 29 Haz 2025, 23:42:32
-- Sunucu sürümü: 10.4.28-MariaDB
-- PHP Sürümü: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `bigol`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `basketball_matches`
--

CREATE TABLE `basketball_matches` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `match_date` date DEFAULT NULL,
  `home1` int(11) DEFAULT NULL,
  `home2` int(11) DEFAULT NULL,
  `home3` int(11) DEFAULT NULL,
  `line_home` decimal(5,2) DEFAULT NULL,
  `away1` int(11) DEFAULT NULL,
  `away2` int(11) DEFAULT NULL,
  `away3` int(11) DEFAULT NULL,
  `line_away` decimal(5,2) DEFAULT NULL,
  `match_line` decimal(5,2) DEFAULT NULL,
  `verdict_match` varchar(100) DEFAULT NULL,
  `verdict_home` varchar(100) DEFAULT NULL,
  `verdict_away` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `football_matches`
--

CREATE TABLE `football_matches` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `match_date` date DEFAULT NULL,
  `score1` varchar(10) DEFAULT NULL,
  `score2` varchar(10) DEFAULT NULL,
  `score3` varchar(10) DEFAULT NULL,
  `home_xg` decimal(4,2) DEFAULT NULL,
  `home_xga` decimal(4,2) DEFAULT NULL,
  `away_xg` decimal(4,2) DEFAULT NULL,
  `away_xga` decimal(4,2) DEFAULT NULL,
  `result` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `best_bet` varchar(50) DEFAULT NULL,
  `best_conf` varchar(10) DEFAULT NULL,
  `second_bet` varchar(50) DEFAULT NULL,
  `second_conf` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `football_matches`
--

INSERT INTO `football_matches` (`id`, `name`, `match_date`, `score1`, `score2`, `score3`, `home_xg`, `home_xga`, `away_xg`, `away_xga`, `result`, `created_at`, `best_bet`, `best_conf`, `second_bet`, `second_conf`) VALUES
(41, 'IK Brage vs Sandvikens IF', '2025-06-27', '2-1', '3-2', '2-2', 1.99, 1.75, 1.80, 1.72, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(78.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(78.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:30:00', 'BTTS Yes', '78.7%', 'Over 2.5', '78.6%'),
(42, 'Varbergs BoIS FC vs Utsikten BK', '2025-06-27', '1-2', '3-1', '3-0', 1.60, 1.29, 1.57, 1.99, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(74.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(63.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:32:11', 'Over 2.5', '74.0%', 'BTTS Yes', '63.8%'),
(43, 'Bohemian FC vs Sligo Rovers FC', '2025-06-27', '2-1', '2-1', '2-0', 1.93, 1.27, 1.35, 2.06, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(74.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(71.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:34:15', 'Away Under 1.5', '74.1%', 'Home Over 1.5', '71.5%'),
(44, 'Cork City FC vs St Patrick\'s Athletic FC', '2025-06-27', '1-1', '0-2', '0-1', 1.53, 1.51, 1.69, 1.55, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(69.3%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Under 2.5</span>\r\n            <span class=\"ml-2\">(59.3%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:35:16', 'Home Under 1.5', '69.3%', 'Under 2.5', '59.3%'),
(45, 'Derry City FC vs Drogheda United FC', '2025-06-27', '1-1', '2-2', '1-1', 1.74, 1.06, 1.33, 1.74, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(71.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(66.1%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:36:36', 'BTTS Yes', '71.0%', 'Away Under 1.5', '66.1%'),
(46, 'Galway United FC vs Shelbourne FC', '2025-06-27', '1-1', '1-1', '0-1', 1.75, 1.70, 1.46, 1.45, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(68.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(68.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:38:09', 'Away Under 1.5', '68.4%', 'Home Under 1.5', '68.0%'),
(47, 'Shamrock Rovers FC vs Waterford FC', '2025-06-27', '3-1', '2-1', '2-0', 1.95, 1.18, 1.16, 1.91, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(77.5%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(70.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:39:55', 'Away Under 1.5', '77.5%', 'Home Over 1.5', '70.5%'),
(48, 'Athlone Town FC vs Bray Wanderers AFC', '2025-06-27', '1-1', '1-1', '0-1', 1.39, 1.18, 1.26, 1.64, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(76.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(70.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:41:13', 'Away Under 1.5', '76.7%', 'Home Under 1.5', '70.0%'),
(49, 'Dundalk FC vs Cobh Ramblers FC', '2025-06-27', '1-1', '1-1', '0-1', 1.79, 0.99, 1.49, 1.41, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(76.2%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(68.1%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:42:47', 'Away Under 1.5', '76.2%', 'Home Under 1.5', '68.1%'),
(50, 'Treaty United FC vs Finn Harps FC', '2025-06-27', '2-0', '3-1', '2-0', 1.63, 1.39, 1.22, 1.65, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(74.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(65.2%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:45:38', 'Away Under 1.5', '74.6%', 'Home Over 1.5', '65.2%'),
(51, 'IF Gnistan vs FC Inter Turku', '2025-06-27', '1-2', '1-2', '1-2', 1.70, 1.84, 1.95, 1.18, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(75.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(75.3%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:48:21', 'BTTS Yes', '75.6%', 'Over 2.5', '75.3%'),
(52, 'Kuopion Palloseura vs Helsingin Jalkapalloklubi', '2025-06-27', '0-1', '2-2', '0-1', 2.00, 1.24, 1.99, 1.41, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(56.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(54.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:50:30', 'Away Under 1.5', '56.6%', 'Home Under 1.5', '54.7%'),
(53, 'Ekenäs IF vs Pallokerho-35', '2025-06-27', '1-1', '2-1', '1-2', 1.54, 0.99, 1.60, 1.35, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(69.9%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(64.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:52:05', 'BTTS Yes', '69.9%', 'Away Under 1.5', '64.0%'),
(54, 'Turun Palloseura vs Järvenpään Palloseura', '2025-06-27', '3-2', '3-1', '3-2', 1.79, 1.66, 1.53, 1.61, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(75.9%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(74.9%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 06:53:06', 'BTTS Yes', '75.9%', 'Over 2.5', '74.9%'),
(55, 'Rosenborg BK vs Viking FK', '2025-06-28', '0-1', '2-1', '0-1', 2.33, 0.72, 1.86, 1.48, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(74.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(51.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:41:19', 'Away Under 1.5', '74.7%', 'BTTS Yes', '51.6%'),
(56, 'IL Hødd vs Mjøndalen IF', '2025-06-28', '2-1', '2-2', '2-0', 1.34, 1.73, 1.10, 1.88, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(64.5%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(62.1%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:42:46', 'Home Over 1.5', '64.5%', 'BTTS Yes', '62.1%'),
(57, 'Kongsvinger IL vs Raufoss IL', '2025-06-28', '3-1', '3-1', '3-0', 2.01, 1.27, 1.48, 2.24, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(76.9%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(73.4%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:43:40', 'Over 2.5', '76.9%', 'Home Over 1.5', '73.4%'),
(58, 'Lillestrøm SK vs Sogndal Fotball', '2025-06-28', '2-1', '3-1', '2-2', 2.13, 1.12, 1.48, 1.59, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(73.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(73.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:45:45', 'BTTS Yes', '73.4%', 'Over 2.5', '73.0%'),
(59, 'Moss FK vs Egersunds IK', '2025-06-28', '2-1', '2-2', '2-0', 1.60, 1.54, 1.29, 1.63, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(64.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(62.1%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:47:14', 'Home Over 1.5', '64.6%', 'BTTS Yes', '62.1%'),
(60, 'Odds BK vs IK Start', '2025-06-28', '2-1', '1-1', '0-1', 1.61, 1.29, 1.69, 1.37, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(70.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(61.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:48:28', 'Away Under 1.5', '70.4%', 'BTTS Yes', '61.8%'),
(61, 'Skeid Fotball vs Aalesunds FK', '2025-06-28', '2-3', '1-3', '1-2', 1.45, 1.95, 1.63, 1.49, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(75.2%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(74.4%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:53:29', 'BTTS Yes', '75.2%', 'Over 2.5', '74.4%'),
(62, 'Stabæk Fotball vs Ranheim Fotball', '2025-06-28', '2-3', '3-2', '1-2', 1.57, 1.47, 1.47, 1.25, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(71.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(69.3%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 07:55:31', 'BTTS Yes', '71.6%', 'Over 2.5', '69.3%'),
(63, 'Seinäjoen Jalkapallokerho vs IFK Mariehamn', '2025-06-28', '3-1', '3-2', '3-0', 1.83, 1.46, 1.20, 2.27, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(75.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(72.4%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 08:03:33', 'Over 2.5', '75.6%', 'Home Over 1.5', '72.4%'),
(64, 'Kotkan Työväen Palloilijat vs FF Jaro', '2025-06-28', '1-2', '1-1', '0-1', 1.67, 2.06, 1.08, 1.80, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(65.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(64.9%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 08:13:16', 'Home Under 1.5', '65.1%', 'BTTS Yes', '64.9%'),
(65, 'GIF Sundsvall vs Östersunds FK', '2025-06-28', '0-1', '0-2', '1-1', 1.67, 1.80, 1.43, 1.63, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(66.9%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Under 2.5</span>\r\n            <span class=\"ml-2\">(57.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 08:40:01', 'Home Under 1.5', '66.9%', 'Under 2.5', '57.6%'),
(66, 'Trelleborgs FF vs IK Oddevold', '2025-06-28', '1-2', '1-3', '0-1', 1.78, 1.13, 1.31, 1.91, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(63.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(61.1%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-26 08:44:07', 'Home Under 1.5', '63.1%', 'BTTS Yes', '61.1%'),
(67, 'DC United vs Nashville SC', '2025-06-29', '2-2', '1-2', '1-2', 1.23, 1.32, 1.60, 1.28, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(69.5%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(66.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-27 23:33:20', 'BTTS Yes', '69.5%', 'Over 2.5', '66.8%'),
(68, 'Montreal Impact vs New York City', '2025-06-29', '0-1', '1-1', '1-1', 1.54, 1.57, 1.26, 1.60, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(72.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(68.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-27 23:34:22', 'Away Under 1.5', '72.1%', 'Home Under 1.5', '68.7%'),
(69, 'New England Revolution vs Colorado Rapids', '2025-06-29', '1-1', '3-1', '1-1', 1.36, 1.56, 0.97, 2.08, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(75.5%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(72.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:28:53', 'Away Under 1.5', '75.5%', 'BTTS Yes', '72.0%'),
(70, 'Orlando City vs FC Cincinnati', '2025-06-29', '2-1', '1-1', '2-2', 1.92, 1.34, 1.66, 1.80, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(76.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(64.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:30:40', 'BTTS Yes', '76.1%', 'Over 2.5', '64.6%'),
(71, 'Toronto vs Portland Timbers', '2025-06-29', '1-2', '0-1', '0-1', 1.30, 1.56, 1.51, 1.63, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(71.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(58.4%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:33:00', 'Home Under 1.5', '71.0%', 'Away Under 1.5', '58.4%'),
(72, ' Chicago Fire vs Charlotte', '2025-06-29', '2-1', '3-1', '2-2', 1.56, 1.61, 1.23, 1.92, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(74.2%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(73.2%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:34:54', 'BTTS Yes', '74.2%', 'Over 2.5', '73.2%'),
(73, 'FC Dallas vs San Diego', '2025-06-29', '2-1', '1-2', '1-2', 1.24, 1.66, 1.67, 1.61, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(73.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(72.3%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:36:38', 'BTTS Yes', '73.7%', 'Over 2.5', '72.3%'),
(74, 'Sporting KC vs Real Salt Lake', '2025-06-29', '2-2', '3-1', '3-1', 1.64, 1.39, 1.57, 1.76, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(74.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(73.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:39:58', 'BTTS Yes', '74.7%', 'Over 2.5', '73.5%'),
(75, 'SJ Earthquakes vs LA Galaxy', '2025-06-29', '5-2', '3-1', '3-1', 2.04, 1.76, 1.20, 1.76, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(76.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(75.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:41:22', 'BTTS Yes', '76.1%', 'Over 2.5', '75.8%'),
(76, 'FK Bodo - Glimt vs Sarpsborg 08', '2025-06-29', '2-1', '4-1', '2-0', 2.02, 0.79, 1.66, 1.64, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(76.3%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(68.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 08:56:13', 'Away Under 1.5', '76.3%', 'Home Over 1.5', '68.8%'),
(77, 'Bryne vs HamKam', '2025-06-29', '1-2', '2-2', '3-1', 1.53, 1.33, 1.13, 2.29, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(72.7%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(72.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:03:11', 'Over 2.5', '72.7%', 'BTTS Yes', '72.7%'),
(78, ' Fredrikstad vs Tromsø', '2025-06-28', '1-2', '0-2', '2-2', 1.11, 1.20, 1.09, 1.66, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(62.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(56.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:05:01', 'Home Under 1.5', '62.0%', 'BTTS Yes', '56.0%'),
(79, 'Haugesund vs Kristiansund', '2025-06-29', '1-4', '1-3', '1-2', 1.30, 2.00, 1.18, 1.99, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(75.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(74.2%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:06:13', 'BTTS Yes', '75.4%', 'Over 2.5', '74.2%'),
(80, 'AIK vs IFK Göteborg', '2025-06-29', '2-1', '3-1', '2-2', 1.74, 1.31, 1.24, 1.69, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(72.1%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(70.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:08:20', 'BTTS Yes', '72.1%', 'Over 2.5', '70.8%'),
(81, 'Häcken vs GAIS', '2025-06-29', '1-1', '1-1', '2-1', 1.97, 1.21, 1.56, 1.26, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(72.8%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(72.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:16:19', 'BTTS Yes', '72.8%', 'Away Under 1.5', '72.7%'),
(82, ' Falkenberg v Umeå', '2025-06-29', '3-0', '2-1', '3-0', 1.90, 1.49, 1.42, 2.18, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(77.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(72.2%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 09:17:33', 'Over 2.5', '77.0%', 'Home Over 1.5', '72.2%'),
(83, 'Panama vs Honduras', '2025-06-29', '4-1', '1-1', '2-1', 1.72, 1.31, 1.55, 1.91, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(74.9%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(71.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-28 20:54:16', 'BTTS Yes', '74.9%', 'Away Under 1.5', '71.5%'),
(84, 'Columbus Crew vs Philadelphia Union', '2025-06-30', '2-1', '2-1', '2-2', 1.88, 1.02, 1.61, 1.44, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(72.2%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(70.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:35:49', 'BTTS Yes', '72.2%', 'Over 2.5', '70.6%');
INSERT INTO `football_matches` (`id`, `name`, `match_date`, `score1`, `score2`, `score3`, `home_xg`, `home_xga`, `away_xg`, `away_xga`, `result`, `created_at`, `best_bet`, `best_conf`, `second_bet`, `second_conf`) VALUES
(85, 'Los Angeles FC vs Vancouver Whitecaps', '2025-06-30', '2-1', '2-1', '2-0', 1.84, 1.27, 1.57, 1.33, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(72.0%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(64.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:37:13', 'Away Under 1.5', '72.0%', 'Home Over 1.5', '64.0%'),
(86, 'Djurgården vs Norrköping', '2025-06-30', '2-2', '1-2', '0-1', 1.58, 1.36, 1.18, 1.97, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(61.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(60.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:41:55', 'BTTS Yes', '61.4%', 'Over 2.5', '60.5%'),
(87, 'Mjällby vs Malmö FF', '2025-06-30', '2-1', '1-0', '2-0', 1.34, 1.42, 1.44, 1.49, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(71.8%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Under 2.5</span>\r\n            <span class=\"ml-2\">(52.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:44:49', 'Away Under 1.5', '71.8%', 'Under 2.5', '52.7%'),
(88, 'Henan Jianye vs Shandong Luneng', '2025-06-30', '2-1', '2-3', '2-4', 1.69, 1.53, 1.88, 1.64, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(76.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(75.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:48:13', 'BTTS Yes', '76.6%', 'Over 2.5', '75.8%'),
(89, 'Dalian Zhixing vs Zhejiang FC', '2025-06-30', '2-1', '0-2', '1-1', 1.76, 1.36, 1.36, 1.72, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(62.5%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(62.2%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:50:18', 'BTTS Yes', '62.5%', 'Away Under 1.5', '62.2%'),
(90, 'Beijing Guoan vs Yunnan Yukun', '2025-06-30', '3-1', '3-0', '1-0', 1.85, 1.14, 1.37, 2.28, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(75.3%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(63.8%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 08:51:49', 'Away Under 1.5', '75.3%', 'Over 2.5', '63.8%'),
(91, 'JK Tallinna Kalev U21 vs FC Tallinn', '2025-06-29', '1-3', '1-2', '3-1', 1.83, 2.46, 1.70, 2.12, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(82.2%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(81.5%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 11:16:14', 'Over 2.5', '82.2%', 'BTTS Yes', '81.5%'),
(92, 'JK Tammeka Tartu II vs Tallinna FC Flora U21', '2025-06-30', '1-3', '1-2', '3-3', 1.51, 2.53, 1.75, 1.88, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(80.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(79.6%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 11:17:48', 'Over 2.5', '80.4%', 'BTTS Yes', '79.6%'),
(93, 'Nõmme Kalju FC U21 vs Tallinna FC Levadia U21', '2025-06-30', '3-1', '1-1', '2-1', 1.83, 2.42, 1.66, 1.66, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(79.6%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Over 2.5</span>\r\n            <span class=\"ml-2\">(69.0%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 11:19:00', 'BTTS Yes', '79.6%', 'Over 2.5', '69.0%'),
(94, 'BFC Daugavpils vs Rīgas FS', '2025-06-30', '1-2', '0-1', '2-1', 1.44, 1.55, 1.99, 1.14, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Home Under 1.5</span>\r\n            <span class=\"ml-2\">(63.8%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">BTTS Yes</span>\r\n            <span class=\"ml-2\">(61.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 11:20:23', 'Home Under 1.5', '63.8%', 'BTTS Yes', '61.7%'),
(95, 'Liepāja vs Grobiņa', '2025-06-30', '2-1', '3-0', '2-0', 1.38, 1.47, 1.00, 1.57, '\r\n      <div class=\"animate__animated animate__fadeIn space-y-4\">\r\n        <div class=\"flex items-center space-x-2 text-football-primary dark:text-football-accent text-xl font-semibold\">\r\n          <i class=\"fas fa-chart-bar\"></i><span>Analysis Result</span>\r\n        </div>\r\n        <div class=\"p-4 bg-football-light dark:bg-football-dark rounded-lg\">\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Best Prediction:</span> \r\n            <span class=\"ml-2\">Away Under 1.5</span>\r\n            <span class=\"ml-2\">(76.4%)</span>\r\n          </p>\r\n          <p class=\"text-football-primary dark:text-football-accent\">\r\n            <span class=\"font-semibold\">Second Best:</span> \r\n            <span class=\"ml-2\">Home Over 1.5</span>\r\n            <span class=\"ml-2\">(61.7%)</span>\r\n          </p>\r\n        </div>\r\n      </div>', '2025-06-29 11:21:57', 'Away Under 1.5', '76.4%', 'Home Over 1.5', '61.7%');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `nba_matches`
--

CREATE TABLE `nba_matches` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `match_date` date DEFAULT NULL,
  `home1` int(11) DEFAULT NULL,
  `home2` int(11) DEFAULT NULL,
  `home3` int(11) DEFAULT NULL,
  `line_home` decimal(5,2) DEFAULT NULL,
  `away1` int(11) DEFAULT NULL,
  `away2` int(11) DEFAULT NULL,
  `away3` int(11) DEFAULT NULL,
  `line_away` decimal(5,2) DEFAULT NULL,
  `match_line` decimal(5,2) DEFAULT NULL,
  `verdict_match` varchar(100) DEFAULT NULL,
  `verdict_home` varchar(100) DEFAULT NULL,
  `verdict_away` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `nba_matches`
--

INSERT INTO `nba_matches` (`id`, `name`, `match_date`, `home1`, `home2`, `home3`, `line_home`, `away1`, `away2`, `away3`, `line_away`, `match_line`, `verdict_match`, `verdict_home`, `verdict_away`, `created_at`) VALUES
(1, 'Indiana - Oklahoma', '2025-06-14', 116, 125, 130, 110.50, 107, 128, 101, 116.50, 226.50, '226.5 NOT RECOMMENDED', '110.5 HOME OVER is PLAYABLE', '116.5 AWAY NOT RECOMMENDED', '2025-06-13 14:34:18');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `ibanConfirm` tinyint(1) NOT NULL DEFAULT 0,
  `role` tinyint(1) NOT NULL DEFAULT 0,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `ibanConfirm`, `role`, `password`, `created_at`, `updated_at`) VALUES
(4, 'HarbiGol', 'test@test.com', 0, 0, '$2y$10$Lx6RtXS.OIlx6IxqfN4Pj.VINqpXvOp84Q/c63tB7PbynlwBiLYcy', '2025-06-29 15:22:40', '2025-06-29 20:42:20'),
(5, 'admin', 'deneme@test.com', 1, 1, '$2y$10$Lx6RtXS.OIlx6IxqfN4Pj.VINqpXvOp84Q/c63tB7PbynlwBiLYcy', '2025-06-29 15:22:40', '2025-06-29 15:22:40');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `basketball_matches`
--
ALTER TABLE `basketball_matches`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `football_matches`
--
ALTER TABLE `football_matches`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `nba_matches`
--
ALTER TABLE `nba_matches`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `basketball_matches`
--
ALTER TABLE `basketball_matches`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Tablo için AUTO_INCREMENT değeri `football_matches`
--
ALTER TABLE `football_matches`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=96;

--
-- Tablo için AUTO_INCREMENT değeri `nba_matches`
--
ALTER TABLE `nba_matches`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- Tablo için AUTO_INCREMENT değeri `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
